# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tuyaliang's Blog
email: tuyaliang@163.com
description: '记录生活' # write a nice description for your blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://tuyaliang.github.io' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
# twitter_username: 'twitter_tuyaliang'

# Build settings
markdown: kramdown

permalink: '/:title/'
highlighter: rouge

gems: [jekyll-paginate]

paginate: 100
